/**
 * Post-build checks for SEO assets:
 * - dist/sitemap.xml must exist (generated by scripts/generate-sitemap.mjs).
 * - dist/llms.txt must exist and look valid.
 */
import { existsSync, readFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const sitemapPath = resolve(root, 'dist', 'sitemap.xml');
if (!existsSync(sitemapPath)) {
  console.error('verify-sitemap: dist/sitemap.xml is missing. Run `node scripts/generate-sitemap.mjs` after build.');
  process.exit(1);
}
const sitemap = readFileSync(sitemapPath, 'utf8');
if (!sitemap.includes('http://www.sitemaps.org/schemas/sitemap/0.9') || !sitemap.includes('https://smlepro.web.app/')) {
  console.error('verify-sitemap: dist/sitemap.xml looks invalid.');
  process.exit(1);
}

const llmsPath = resolve(root, 'dist', 'llms.txt');
if (!existsSync(llmsPath)) {
  console.error('verify-sitemap: dist/llms.txt is missing. Add public/llms.txt and rebuild.');
  process.exit(1);
}
const llms = readFileSync(llmsPath, 'utf8');
if (!llms.includes('SMLE Pro') || !llms.includes('https://smlepro.web.app')) {
  console.error('verify-sitemap: dist/llms.txt looks invalid.');
  process.exit(1);
}

console.log('verify-sitemap: OK (sitemap.xml + llms.txt)');
