/**
 * Diagnostic Quiz Data — 40 SMLE-style questions for the weakness assessment.
 * 4 Domains weighted by SMLE blueprint:
 *   Medicine    (10 questions × ~3% each = 30%)
 *   OBGYN       (10 questions × ~2.5% each = 25%)
 *   Pediatrics  (10 questions × ~2.5% each = 25%)
 *   Surgery     (8  questions × ~2.5% each = 20%)
 *   Cross-Cutting (2 questions × ~2.5% each = 5%)
 *
 * Questions are SMLE-hard difficulty. Each has a clear stem, 4 options,
 * one correct answer, and a 2-sentence explanation.
 *
 * Domain weight map used by diagnosticResults.js for weakness calculation.
 */
export const DIAGNOSTIC_DOMAIN_WEIGHTS = {
  Medicine: 0.30,
  OBGYN: 0.25,
  Pediatrics: 0.25,
  Surgery: 0.20,
  // CrossCutting bonus questions weighted separately
};

export const DIAGNOSTIC_QUESTIONS = [
  // ── Medicine (10 questions) ─────────────────────────────────────────────
  {
    id: 'dx_med_01',
    domain: 'Medicine',
    subtopic: 'Cardiology',
    question: 'A 58-year-old man with a 30-pack-year smoking history presents with acute onset tearing chest pain radiating to his back. BP is 210/110 mmHg in the right arm and 150/80 mmHg in the left arm. CXR shows a widened mediastinum. What is the most appropriate next step?',
    options: [
      { text: 'Coronary angiography', correct: false },
      { text: 'CT angiography of the chest', correct: true },
      { text: 'Ventilation-perfusion scan', correct: false },
      { text: 'Transthoracic echocardiogram', correct: false },
    ],
    explanation: 'This presentation is classic for aortic dissection (tearing chest pain, pulse deficit, widened mediastinum). CT angiography is the gold standard for diagnosis. Coronary angiography is indicated for ACS, not dissection.',
  },
  {
    id: 'dx_med_02',
    domain: 'Medicine',
    subtopic: 'Respiratory',
    question: 'A 45-year-old woman with a history of asthma presents with progressive dyspnea, dry cough, and bilateral wheezing over 3 weeks. She has no fever. PFTs show FEV₁/FVC < 0.70 with bronchodilator reversibility. What is the most likely diagnosis?',
    options: [
      { text: 'Chronic obstructive pulmonary disease', correct: false },
      { text: 'Allergic bronchopulmonary aspergillosis', correct: false },
      { text: 'Asthma exacerbation', correct: true },
      { text: 'Hypersensitivity pneumonitis', correct: false },
    ],
    explanation: 'This patient has known asthma with obstructive PFTs (low FEV₁/FVC) that are reversible — consistent with an asthma exacerbation. ABPA presents with refractory asthma, eosinophilia, and radiographic infiltrates. COPD typically lacks full reversibility.',
  },
  {
    id: 'dx_med_03',
    domain: 'Medicine',
    subtopic: 'Gastroenterology',
    question: 'A 62-year-old man presents with epigastric pain, early satiety, and unintentional weight loss of 8 kg over 2 months. He has a 15-year history of GERD treated with omeprazole. EGD reveals an ulcerated mass in the gastric antrum. Biopsy shows signet ring cells. Which of the following is the most likely diagnosis?',
    options: [
      { text: 'Gastric adenocarcinoma, intestinal type', correct: false },
      { text: 'Gastric adenocarcinoma, diffuse type', correct: true },
      { text: 'Gastrointestinal stromal tumor', correct: false },
      { text: 'Mucosa-associated lymphoid tissue lymphoma', correct: false },
    ],
    explanation: 'Signet ring cells are characteristic of diffuse-type gastric adenocarcinoma (Laurén classification). This type carries a worse prognosis than intestinal-type and is not associated with Helicobacter pylori as strongly. GISTs are mesenchymal tumors, not epithelial.',
  },
  {
    id: 'dx_med_04',
    domain: 'Medicine',
    subtopic: 'Nephrology',
    question: 'A 34-year-old woman presents with foamy urine and bilateral lower extremity edema. Urinalysis shows 4+ protein but no hematuria. Serum albumin is 2.1 g/dL (normal 3.5-5.0). Renal biopsy shows diffuse foot process effacement on electron microscopy with no immune deposits. What is the most likely diagnosis?',
    options: [
      { text: 'Focal segmental glomerulosclerosis', correct: false },
      { text: 'Minimal change disease', correct: true },
      { text: 'Membranous nephropathy', correct: false },
      { text: 'IgA nephropathy', correct: false },
    ],
    explanation: 'This is classic nephrotic syndrome (foamy urine, proteinuria, hypoalbuminemia, edema) with biopsy showing foot process effacement and no immune deposits — pathognomonic for minimal change disease. FSGS shows segmental sclerosis, and membranous has subepithelial deposits.',
  },
  {
    id: 'dx_med_05',
    domain: 'Medicine',
    subtopic: 'Endocrinology',
    question: 'A 28-year-old woman presents with palpitations, heat intolerance, and weight loss despite increased appetite over 3 months. Exam shows a diffuse goiter, lid lag, and fine tremor. TSH is <0.01 mIU/L and free T4 is 4.2 ng/dL (normal 0.8-1.8). Which of the following is the most appropriate first-line treatment?',
    options: [
      { text: 'Radioactive iodine ablation', correct: false },
      { text: 'Subtotal thyroidectomy', correct: false },
      { text: 'Methimazole', correct: true },
      { text: 'Propranolol monotherapy', correct: false },
    ],
    explanation: 'This is Graves disease with overt hyperthyroidism. Methimazole (thionamide) is first-line medical therapy in young patients. Propranolol is an adjunct for symptom control. RAI is avoided in pregnancy and patients with ophthalmopathy. Surgery is second-line.',
  },
  {
    id: 'dx_med_06',
    domain: 'Medicine',
    subtopic: 'Infectious Disease',
    question: 'A 30-year-old man who injects drugs presents with fever, chills, and a new-onset holosystolic murmur best heard at the left lower sternal border. Blood cultures grow Staphylococcus aureus. TEE reveals a 1.2 cm vegetation on the tricuspid valve. What is the most likely source of the vegetation?',
    options: [
      { text: 'Septic emboli from IV drug use', correct: false },
      { text: 'Infective endocarditis of the tricuspid valve', correct: true },
      { text: 'Myxomatous degeneration of the tricuspid valve', correct: false },
      { text: 'Rheumatic heart disease affecting the tricuspid valve', correct: false },
    ],
    explanation: 'IV drug users are at high risk for right-sided infective endocarditis, typically caused by S. aureus affecting the tricuspid valve. The tricuspid vegetation on TEE and IVDU history are classic. Myxomatous degeneration and rheumatic disease affect the mitral valve more commonly.',
  },
  {
    id: 'dx_med_07',
    domain: 'Medicine',
    subtopic: 'Rheumatology',
    question: 'A 40-year-old woman presents with symmetric morning stiffness lasting >1 hour in her wrists and metacarpophalangeal joints for 6 weeks. She also has subcutaneous nodules over the extensor surfaces of her forearms. RF and anti-CCP antibodies are positive. Which of the following is the most likely diagnosis?',
    options: [
      { text: 'Systemic lupus erythematosus', correct: false },
      { text: 'Rheumatoid arthritis', correct: true },
      { text: 'Psoriatic arthritis', correct: false },
      { text: 'Osteoarthritis', correct: false },
    ],
    explanation: 'Symmetric small joint arthritis with morning stiffness >30 minutes, rheumatoid nodules, and positive RF plus anti-CCP is classic for rheumatoid arthritis. SLE typically has positive ANA and anti-dsDNA. Psoriatic arthritis involves DIP joints and has skin findings.',
  },
  {
    id: 'dx_med_08',
    domain: 'Medicine',
    subtopic: 'Hematology-Oncology',
    question: 'A 65-year-old man presents with fatigue, pallor, and easy bruising. CBC shows Hb 8.2 g/dL, WBC 2,000/µL, platelets 35,000/µL. Peripheral smear shows no blasts. Bone marrow biopsy shows a hypercellular marrow with <5% blasts and dysplastic changes in all three cell lines. Which of the following is the most likely diagnosis?',
    options: [
      { text: 'Aplastic anemia', correct: false },
      { text: 'Myelodysplastic syndrome', correct: true },
      { text: 'Acute myeloid leukemia', correct: false },
      { text: 'Chronic myeloid leukemia', correct: false },
    ],
    explanation: 'This patient has pancytopenia with a hypercellular marrow showing trilineage dysplasia and <5% blasts — diagnostic of myelodysplastic syndrome (MDS). Aplastic anemia would show a hypocellular marrow. AML has >20% blasts. CML has leukocytosis with the Philadelphia chromosome.',
  },
  {
    id: 'dx_med_09',
    domain: 'Medicine',
    subtopic: 'Neurology',
    question: 'A 75-year-old man with hypertension and diabetes presents with sudden-onset difficulty speaking and right-sided weakness. Symptoms started 2 hours ago. CT head shows no hemorrhage. NIHSS score is 14. What is the most appropriate treatment if no contraindications exist?',
    options: [
      { text: 'Intravenous alteplase (tPA)', correct: true },
      { text: 'Aspirin 325 mg daily', correct: false },
      { text: 'Intravenous heparin infusion', correct: false },
      { text: 'Emergent carotid endarterectomy', correct: false },
    ],
    explanation: 'This is an acute ischemic stroke within the 4.5-hour window for IV tPA (alteplase) after CT has ruled out hemorrhage. Aspirin alone is not sufficient acute treatment. Heparin is not indicated for acute stroke. Endarterectomy is for chronic stenosis, not acute management.',
  },
  {
    id: 'dx_med_10',
    domain: 'Medicine',
    subtopic: 'Dermatology',
    question: 'A 50-year-old woman presents with a pruritic, well-demarcated, erythematous rash with silvery scales on her elbows, knees, and scalp. She has been using over-the-counter moisturizers for weeks with no improvement. Nail pitting is noted on physical exam. What is the most likely diagnosis?',
    options: [
      { text: 'Atopic dermatitis', correct: false },
      { text: 'Psoriasis vulgaris', correct: true },
      { text: 'Seborrheic dermatitis', correct: false },
      { text: 'Contact dermatitis', correct: false },
    ],
    explanation: 'Psoriasis vulgaris presents with well-demarcated, erythematous plaques with silvery scale on extensor surfaces, scalp involvement, and nail pitting — all present here. Atopic dermatitis involves flexural surfaces. Seborrheic dermatitis has greasy scale on the face and scalp.',
  },

  // ── OBGYN (10 questions) ────────────────────────────────────────────────
  {
    id: 'dx_obgyn_01',
    domain: 'OBGYN',
    subtopic: 'Antenatal Care',
    question: 'A 28-year-old G1P0 at 28 weeks gestation presents with a blood pressure of 155/105 mmHg and 2+ proteinuria on dipstick. She complains of a frontal headache. Serum creatinine is 0.9 mg/dL. Which of the following is the most appropriate next step in management?',
    options: [
      { text: 'Deliver immediately by cesarean section', correct: false },
      { text: 'Oral labetalol for BP control and close monitoring', correct: false },
      { text: 'IV magnesium sulfate, IV labetalol, and plan for delivery', correct: true },
      { text: 'Start hydralazine and reschedule in one week', correct: false },
    ],
    explanation: 'This is severe preeclampsia (BP ≥160/110 or with symptoms) at 28 weeks. Management requires IV magnesium for seizure prophylaxis, antihypertensives (labetalol or hydralazine), and delivery. Immediate delivery is indicated for severe features at this gestational age.',
  },
  {
    id: 'dx_obgyn_02',
    domain: 'OBGYN',
    subtopic: 'Postnatal',
    question: 'A 32-year-old G3P3 presents 3 days postpartum with heavy vaginal bleeding, fever of 38.9°C, and foul-smelling lochia. Uterus is tender and boggy on exam. WBC is 18,000/µL. What is the most likely diagnosis?',
    options: [
      { text: 'Endometritis', correct: true },
      { text: 'Retained placental fragments', correct: false },
      { text: 'Uterine atony', correct: false },
      { text: 'Vaginal hematoma', correct: false },
    ],
    explanation: 'Postpartum endometritis presents with fever, foul-smelling lochia, and uterine tenderness, especially after cesarean delivery. Retained fragments cause hemorrhage without fever. Atony occurs immediately postpartum. Hematoma presents with perineal pain and a mass.',
  },
  {
    id: 'dx_obgyn_03',
    domain: 'OBGYN',
    subtopic: 'Labor and Delivery',
    question: 'A 24-year-old G1P0 at 39 weeks is in active labor. Contractions are 3 minutes apart. Cervical exam shows 5 cm dilation, 80% effacement, and station 0. The fetal heart rate shows variable decelerations dropping to 90 bpm that recover slowly, occurring with each contraction. What is the most likely cause?',
    options: [
      { text: 'Uteroplacental insufficiency', correct: false },
      { text: 'Cord compression', correct: true },
      { text: 'Head compression', correct: false },
      { text: 'Maternal hypotension', correct: false },
    ],
    explanation: 'Variable decelerations that correlate with contractions are classic for umbilical cord compression. Late decelerations indicate uteroplacental insufficiency. Early decelerations are from head compression and are benign. Management includes repositioning and amnioinfusion.',
  },
  {
    id: 'dx_obgyn_04',
    domain: 'OBGYN',
    subtopic: 'Contraception',
    question: 'A 34-year-old G2P2 with a history of deep vein thrombosis 6 months ago requests contraception. She smokes 10 cigarettes daily. Which contraceptive method is contraindicated in this patient?',
    options: [
      { text: 'Copper intrauterine device', correct: false },
      { text: 'Combined oral contraceptive pill', correct: true },
      { text: 'Progestin-only implant', correct: false },
      { text: 'Levonorgestrel IUD', correct: false },
    ],
    explanation: 'Combined hormonal contraceptives (estrogen-containing) are contraindicated in women with a history of DVT due to increased thromboembolic risk, especially with smoking >35 years. Progestin-only methods (implant, LNG-IUD) and copper IUD are safe alternatives.',
  },
  {
    id: 'dx_obgyn_05',
    domain: 'OBGYN',
    subtopic: 'Menstrual Disorders',
    question: 'A 17-year-old nulligravida presents with cyclic pelvic pain for 2 years, worsening during menstruation. She has dysmenorrhea that is unresponsive to NSAIDs. Pelvic ultrasound is normal. She has a family history of endometriosis. What is the most likely diagnosis?',
    options: [
      { text: 'Polycystic ovary syndrome', correct: false },
      { text: 'Endometriosis', correct: true },
      { text: 'Pelvic inflammatory disease', correct: false },
      { text: 'Ovarian torsion', correct: false },
    ],
    explanation: 'Cyclic pelvic pain with dysmenorrhea unresponsive to NSAIDs, normal ultrasound, and positive family history is most consistent with endometriosis. PCOS presents with irregular periods and hyperandrogenism. PID has infectious etiology. Ovarian torsion is acute and severe.',
  },
  {
    id: 'dx_obgyn_06',
    domain: 'OBGYN',
    subtopic: 'Gynecologic Oncology',
    question: 'A 50-year-old woman presents with postmenopausal bleeding for 1 month. BMI is 35. Endometrial biopsy shows atypical endometrial hyperplasia. Which of the following is the most appropriate definitive management?',
    options: [
      { text: 'Progesterone therapy with surveillance biopsy', correct: false },
      { text: 'Total abdominal hysterectomy with bilateral salpingo-oophorectomy', correct: true },
      { text: 'Dilation and curettage with hysteroscopy', correct: false },
      { text: 'Radiation therapy', correct: false },
    ],
    explanation: 'Atypical endometrial hyperplasia is a precursor to endometrioid adenocarcinoma. Definitive management is hysterectomy with BSO, especially in a postmenopausal woman with obesity. Progestin therapy is reserved for those who wish to preserve fertility. Radiation is for cancer.',
  },
  {
    id: 'dx_obgyn_07',
    domain: 'OBGYN',
    subtopic: 'Infertility',
    question: 'A 32-year-old woman presents with primary infertility for 18 months. She has irregular menses every 35-45 days, hirsutism, and acne. Her BMI is 28. LH:FSH ratio is 3:1. What is the most likely diagnosis?',
    options: [
      { text: 'Hypothalamic amenorrhea', correct: false },
      { text: 'Polycystic ovary syndrome', correct: true },
      { text: 'Premature ovarian insufficiency', correct: false },
      { text: 'Hyperprolactinemia', correct: false },
    ],
    explanation: 'Infertility with oligomenorrhea, hyperandrogenism (hirsutism, acne), elevated LH:FSH ratio >2:1, and obesity is classic for PCOS using Rotterdam criteria. Hypothalamic amenorrhea has low LH/FSH. Premature ovarian insufficiency has elevated FSH and low estradiol.',
  },
  {
    id: 'dx_obgyn_08',
    domain: 'OBGYN',
    subtopic: 'Antenatal Screening',
    question: 'A 35-year-old G2P1 at 12 weeks gestation undergoes first-trimester screening. Nuchal translucency is 4.5 mm (>99th percentile). Which chromosomal abnormality is this finding most strongly associated with?',
    options: [
      { text: 'Turner syndrome (45,X)', correct: false },
      { text: 'Down syndrome (Trisomy 21)', correct: true },
      { text: 'Edwards syndrome (Trisomy 18)', correct: false },
      { text: 'Klinefelter syndrome (47,XXY)', correct: false },
    ],
    explanation: 'Increased nuchal translucency >3.5 mm is most strongly associated with trisomy 21 (Down syndrome), as well as trisomies 13 and 18, Turner syndrome, and congenital heart defects. The most common associated aneuploidy at this NT measurement is Trisomy 21.',
  },
  {
    id: 'dx_obgyn_09',
    domain: 'OBGYN',
    subtopic: 'Labor Complications',
    question: 'A 29-year-old G2P1 at 38 weeks presents with a cord prolapse after spontaneous rupture of membranes at home. The fetal heart rate is 80 bpm. The cervix is 6 cm dilated. What is the most appropriate immediate action?',
    options: [
      { text: 'Perform an emergency cesarean section', correct: false },
      { text: 'Relieve cord compression by lifting the presenting part and call for emergency cesarean', correct: true },
      { text: 'Administer oxytocin to expedite delivery', correct: false },
      { text: 'Attempt to push the cord back into the uterus', correct: false },
    ],
    explanation: 'Umbilical cord prolapse requires immediate relief of cord compression by lifting the presenting part off the cord (knee-chest or Trendelenburg position) while preparing for emergency cesarean. Never push the cord back or give oxytocin, which worsens compression.',
  },
  {
    id: 'dx_obgyn_10',
    domain: 'OBGYN',
    subtopic: 'Breast Disease',
    question: 'A 45-year-old woman finds a firm, immobile, 2 cm breast mass on self-exam. She has no family history of breast cancer. Mammogram shows a spiculated mass with microcalcifications. Core needle biopsy reveals invasive ductal carcinoma with positive estrogen and progesterone receptors, HER2-negative. What is the most appropriate surgical management?',
    options: [
      { text: 'Breast-conserving surgery with sentinel lymph node biopsy', correct: true },
      { text: 'Simple mastectomy without lymph node evaluation', correct: false },
      { text: 'Radical mastectomy', correct: false },
      { text: 'Excisional biopsy with observation', correct: false },
    ],
    explanation: 'For early-stage (2 cm) ER+/HER2-negative invasive ductal carcinoma, breast-conserving surgery (lumpectomy) with sentinel lymph node biopsy and radiation is standard. Simple mastectomy is for multicentric disease or contraindications to radiation. Radical mastectomy is rarely needed.',
  },

  // ── Pediatrics (10 questions) ───────────────────────────────────────────
  {
    id: 'dx_peds_01',
    domain: 'Pediatrics',
    subtopic: 'Growth and Development',
    question: 'An 18-month-old child is brought for a well-child visit. The mother reports the child speaks 3 single words, walks independently, and uses a spoon. Which of the following developmental milestones should the child have achieved by this age that the mother did not mention?',
    options: [
      { text: 'Runs and climbs stairs with help', correct: true },
      { text: 'Pedals a tricycle', correct: false },
      { text: 'Says 3-word sentences', correct: false },
      { text: 'Copies a circle', correct: false },
    ],
    explanation: 'By 18 months, a child should walk independently, speak 5-10 words, and run/climb stairs with help. Tricycle pedaling is expected by age 3. 3-word sentences appear around 2-3 years. Copying a circle is a 3-year milestone.',
  },
  {
    id: 'dx_peds_02',
    domain: 'Pediatrics',
    subtopic: 'Neonatology',
    question: 'A 35-week-gestation newborn develops respiratory distress immediately after delivery, with grunting, tachypnea, and nasal flaring. CXR shows diffuse bilateral reticulogranular opacities. The mother had no prenatal care. What is the most likely diagnosis?',
    options: [
      { text: 'Congenital pneumonia', correct: false },
      { text: 'Neonatal respiratory distress syndrome', correct: true },
      { text: 'Meconium aspiration syndrome', correct: false },
      { text: 'Transient tachypnea of the newborn', correct: false },
    ],
    explanation: 'This preterm infant (35 weeks) with early respiratory distress and the classic CXR finding of reticulogranular opacities (ground glass) is diagnostic of respiratory distress syndrome due to surfactant deficiency. TTN is more common in term infants after cesarean delivery.',
  },
  {
    id: 'dx_peds_03',
    domain: 'Pediatrics',
    subtopic: 'Infectious Disease',
    question: 'A 4-year-old child presents with fever, cough, and "barking" stridor that worsens at night. Symptoms started 2 days ago. The child appears anxious, with mild intercostal retractions. What is the most likely diagnosis?',
    options: [
      { text: 'Bacterial tracheitis', correct: false },
      { text: 'Croup (laryngotracheobronchitis)', correct: true },
      { text: 'Epiglottitis', correct: false },
      { text: 'Bronchiolitis', correct: false },
    ],
    explanation: 'Croup presents with a classic barking cough, stridor, and hoarseness in children aged 6 months to 3 years, often worse at night. Epiglottitis has drooling and a toxic appearance with a muffled voice. Bacterial tracheitis is a more severe, high-fever illness.',
  },
  {
    id: 'dx_peds_04',
    domain: 'Pediatrics',
    subtopic: 'Genetics',
    question: 'A newborn has a characteristic high-pitched cry, microcephaly, downward-slanting palpebral fissures, micrognathia, and hypotonia. Which of the following genetic abnormalities is most likely?',
    options: [
      { text: 'Deletion on chromosome 5p (Cri-du-chat syndrome)', correct: true },
      { text: 'Deletion on chromosome 15q (Angelman syndrome)', correct: false },
      { text: 'Deletion on chromosome 22q (DiGeorge syndrome)', correct: false },
      { text: 'Deletion on chromosome 7q (Williams syndrome)', correct: false },
    ],
    explanation: 'Cri-du-chat syndrome is caused by a deletion of the short arm of chromosome 5 (5p-). The cat-like cry, microcephaly, and dysmorphic facies are classic. DiGeorge (22q11.2) presents with cardiac defects and T-cell deficiency. Williams (7q11.23) has elfin facies.',
  },
  {
    id: 'dx_peds_05',
    domain: 'Pediatrics',
    subtopic: 'Cardiology',
    question: 'A 3-day-old full-term infant is cyanotic and tachypneic. Crying increases the cyanosis. Cardiac exam reveals a single S2 with a harsh holosystolic murmur at the left lower sternal border. Chest X-ray shows a boot-shaped heart. What is the most likely diagnosis?',
    options: [
      { text: 'Ventricular septal defect', correct: false },
      { text: 'Tetralogy of Fallot', correct: true },
      { text: 'Transposition of the great arteries', correct: false },
      { text: 'Patent ductus arteriosus', correct: false },
    ],
    explanation: 'Tetralogy of Fallot (RVH, VSD, overriding aorta, pulmonic stenosis) classically presents with cyanosis worsening with crying (tet spells), a boot-shaped heart on CXR, and a single S2 with a pulmonic stenosis murmur. VSD alone causes a loud murmur but not cyanosis early.',
  },
  {
    id: 'dx_peds_06',
    domain: 'Pediatrics',
    subtopic: 'Respiratory',
    question: 'A 2-year-old child presents in November with wheezing, tachypnea, and intercostal retractions. He had a runny nose and low-grade fever for 2 days prior. RSV nasal swab is positive. Pulse oximetry shows 90% on room air. What is the most appropriate management?',
    options: [
      { text: 'Oral prednisolone and discharge home', correct: false },
      { text: 'Albuterol nebulizer and discharge if improving', correct: false },
      { text: 'Supplemental oxygen, suction, and monitoring', correct: true },
      { text: 'Intravenous antibiotics and chest physiotherapy', correct: false },
    ],
    explanation: 'Bronchiolitis management is supportive: oxygen for saturations <90%, nasal suctioning, and monitoring. Albuterol is not routinely recommended. Steroids are not indicated for bronchiolitis. Antibiotics are for bacterial infection, and RSV is viral.',
  },
  {
    id: 'dx_peds_07',
    domain: 'Pediatrics',
    subtopic: 'Gastroenterology',
    question: 'A 6-week-old infant presents with projectile non-bilious vomiting after feeds for 1 week. The infant is hungry and feeds again after vomiting. On exam, a small olive-shaped mass is felt in the right upper quadrant. What is the most likely diagnosis?',
    options: [
      { text: 'Gastroesophageal reflux disease', correct: false },
      { text: 'Pyloric stenosis', correct: true },
      { text: 'Intussusception', correct: false },
      { text: 'Malrotation with volvulus', correct: false },
    ],
    explanation: 'Pyloric stenosis presents at 2-8 weeks with projectile, non-bilious vomiting, an olive-shaped mass in the RUQ (hypertrophied pylorus), and hungry infants. GER presents with non-projectile spitting. Intussusception has currant jelly stools and bilious vomiting.',
  },
  {
    id: 'dx_peds_08',
    domain: 'Pediatrics',
    subtopic: 'Neurology',
    question: 'A 6-year-old child presents with brief episodes of staring and unresponsiveness lasting 10 seconds, occurring 20 times per day. During the episodes, the child blinks rapidly and drops objects. EEG shows generalized 3 Hz spike-and-wave discharges. What is the most likely diagnosis?',
    options: [
      { text: 'Juvenile myoclonic epilepsy', correct: false },
      { text: 'Complex partial seizures', correct: false },
      { text: 'Childhood absence epilepsy', correct: true },
      { text: 'Febrile seizures', correct: false },
    ],
    explanation: 'Childhood absence epilepsy presents with brief staring spells, 3 Hz spike-and-wave on EEG, and onset at 4-8 years. JME has myoclonic jerks on awakening. Complex partial seizures have altered consciousness with automatisms and focal EEG findings.',
  },
  {
    id: 'dx_peds_09',
    domain: 'Pediatrics',
    subtopic: 'Infectious Disease',
    question: 'A 5-year-old unvaccinated child presents with fever, malaise, and a maculopapular rash that started on the face and spread downward over 3 days. Koplik spots are visible on the buccal mucosa. Which complication is most concerning in this patient?',
    options: [
      { text: 'Otitis media', correct: false },
      { text: 'Subacute sclerosing panencephalitis', correct: true },
      { text: 'Febrile seizures', correct: false },
      { text: 'Bronchiolitis', correct: false },
    ],
    explanation: 'This is measles (rubeola). While otitis media and pneumonia are acute complications, subacute sclerosing panencephalitis (SSPE) is a rare but fatal degenerative CNS complication that occurs years after infection. SSPE is prevented by vaccination.',
  },
  {
    id: 'dx_peds_10',
    domain: 'Pediatrics',
    subtopic: 'Immunizations',
    question: 'A 2-month-old infant is due for routine immunizations. Which of the following vaccines should be administered at this visit according to the Saudi Ministry of Health immunization schedule?',
    options: [
      { text: 'MMR and varicella', correct: false },
      { text: 'Hepatitis B, DTaP, IPV, Hib, PCV13, and Rotavirus', correct: true },
      { text: 'Tdap and HPV', correct: false },
      { text: 'Influenza and meningococcal conjugate', correct: false },
    ],
    explanation: 'The Saudi immunization schedule recommends at 2 months: Hepatitis B (2nd dose), DTaP, IPV, Hib, PCV13, and Rotavirus (1st dose). MMR is given at 12 months. HPV starts at 11-12 years. Tdap is a booster at 4-6 years.',
  },

  // ── Surgery (8 questions) ───────────────────────────────────────────────
  {
    id: 'dx_surg_01',
    domain: 'Surgery',
    subtopic: 'General Surgery',
    question: 'A 55-year-old woman presents with acute right upper quadrant pain radiating to the right shoulder, nausea, and fever of 38.5°C. Murphy sign is positive. WBC is 15,000/µL. Right upper quadrant ultrasound shows a distended gallbladder with a thickened wall and pericholecystic fluid. What is the most appropriate management?',
    options: [
      { text: 'Elective cholecystectomy after symptomatic treatment', correct: false },
      { text: 'Laparoscopic cholecystectomy within 72 hours', correct: true },
      { text: 'ERCP with sphincterotomy', correct: false },
      { text: 'Percutaneous cholecystostomy tube', correct: false },
    ],
    explanation: 'This is acute cholecystitis (Murphy sign, fever, thickened GB wall). Early laparoscopic cholecystectomy within 72 hours is the standard of care. ERCP is for choledocholithiasis. Percutaneous drainage is reserved for critically ill patients who cannot undergo surgery.',
  },
  {
    id: 'dx_surg_02',
    domain: 'Surgery',
    subtopic: 'Trauma',
    question: 'A 28-year-old man is brought to the emergency department after a high-speed motor vehicle collision. He is hypotensive (BP 80/50 mmHg), tachycardic (HR 130 bpm), and has a distended, rigid abdomen. FAST exam shows free fluid in the right upper quadrant. What is the most appropriate next step?',
    options: [
      { text: 'CT abdomen with IV contrast', correct: false },
      { text: 'Diagnostic peritoneal lavage', correct: false },
      { text: 'Emergent exploratory laparotomy', correct: true },
      { text: 'Angiography with embolization', correct: false },
    ],
    explanation: 'A hypotensive patient with a positive FAST (free intra-abdominal fluid) after trauma has hemorrhagic shock and requires emergent laparotomy. CT is time-consuming and inappropriate in an unstable patient. DPL has been replaced by FAST. Angioembolization is for stable patients.',
  },
  {
    id: 'dx_surg_03',
    domain: 'Surgery',
    subtopic: 'Orthopedics',
    question: 'A 75-year-old woman with osteoporosis slips on a wet floor and falls onto her outstretched right hand. She presents with wrist pain, swelling, and a "dinner fork" deformity. Which fracture is most likely?',
    options: [
      { text: 'Smith fracture of the distal radius', correct: false },
      { text: 'Colles fracture of the distal radius', correct: true },
      { text: 'Scaphoid fracture', correct: false },
      { text: 'Barton fracture of the distal radius', correct: false },
    ],
    explanation: 'A Colles fracture is a dorsally angulated distal radius fracture from a fall on an outstretched hand, classically producing a "dinner fork" deformity. Smith fracture is volarly angulated (reverse). Scaphoid fractures present with snuffbox tenderness. Barton is an intra-articular fracture.',
  },
  {
    id: 'dx_surg_04',
    domain: 'Surgery',
    subtopic: 'Endocrine Surgery',
    question: 'A 42-year-old woman presents with palpitations, heat intolerance, and a 3 cm thyroid nodule. Thyroid ultrasound shows a solid, hypoechoic nodule with microcalcifications. TSH is suppressed. Fine-needle aspiration is suspicious for papillary thyroid carcinoma. What is the most appropriate surgical management?',
    options: [
      { text: 'Left thyroid lobectomy', correct: false },
      { text: 'Total thyroidectomy', correct: true },
      { text: 'Radioactive iodine ablation', correct: false },
      { text: 'Thyroid nodule enucleation', correct: false },
    ],
    explanation: 'Total thyroidectomy is indicated for papillary thyroid carcinoma >1 cm, especially with suspicious features (microcalcifications, hypoechoic, suspicious FNA). Lobectomy may be considered for <1 cm unifocal tumors. RAI is adjuvant, not primary treatment.',
  },
  {
    id: 'dx_surg_05',
    domain: 'Surgery',
    subtopic: 'Colorectal',
    question: 'A 60-year-old man presents with a 3-month history of rectal bleeding, tenesmus, and a sensation of incomplete evacuation. Digital rectal exam reveals a hard, fixed mass 6 cm from the anal verge. Biopsy shows adenocarcinoma. What is the most reliable staging modality before treatment?',
    options: [
      { text: 'CT scan of the abdomen and pelvis', correct: false },
      { text: 'Endorectal ultrasound or pelvic MRI', correct: true },
      { text: 'PET-CT scan', correct: false },
      { text: 'Carcinoembryonic antigen (CEA) level', correct: false },
    ],
    explanation: 'For rectal cancer, endorectal ultrasound or pelvic MRI are the most reliable for local staging (T-stage and nodal involvement) to determine neoadjuvant chemoradiation. CT is better for distant metastasis. CEA is a tumor marker for monitoring, not staging.',
  },
  {
    id: 'dx_surg_06',
    domain: 'Surgery',
    subtopic: 'Vascular',
    question: 'A 70-year-old man with a 50-pack-year smoking history presents with a pulsatile abdominal mass found incidentally on physical exam. He is asymptomatic. CT angiography shows a 5.5 cm infrarenal abdominal aortic aneurysm. What is the most appropriate management?',
    options: [
      { text: 'Serial ultrasound surveillance every 6-12 months', correct: false },
      { text: 'Elective endovascular or open repair', correct: true },
      { text: 'Medical management with beta-blockers and smoking cessation', correct: false },
      { text: 'Urgent surgical repair', correct: false },
    ],
    explanation: 'The threshold for elective AAA repair is 5.5 cm in men (5.0 cm in women) due to increased rupture risk above this size. EVAR or open repair are the options. Surveillance is for aneurysms <5.5 cm. Urgent repair is for symptomatic or ruptured AAA.',
  },
  {
    id: 'dx_surg_07',
    domain: 'Surgery',
    subtopic: 'Breast Surgery',
    question: 'A 38-year-old woman presents with purulent nipple discharge from the left breast for 3 days. She is breastfeeding. The breast is erythematous, warm, and tender in the upper outer quadrant with a palpable, fluctuant mass. What is the most appropriate management?',
    options: [
      { text: 'Oral antibiotics and continued breastfeeding', correct: false },
      { text: 'Incision and drainage with antibiotics', correct: true },
      { text: 'Needle aspiration and sentinel node biopsy', correct: false },
      { text: 'Mammogram and breast MRI', correct: false },
    ],
    explanation: 'This is a lactational breast abscess (fluctuant mass with purulent discharge). Treatment is incision and drainage plus antibiotics (usually coverage for S. aureus). Continued breastfeeding from the unaffected breast is encouraged. Imaging is not needed for this clinical picture.',
  },
  {
    id: 'dx_surg_08',
    domain: 'Surgery',
    subtopic: 'Urology',
    question: 'A 65-year-old man presents with difficulty starting urination, weak stream, and nocturia for 6 months. Digital rectal exam reveals a symmetrically enlarged, firm, smooth prostate. PSA is 4.5 ng/mL (normal <4.0). What is the most likely diagnosis?',
    options: [
      { text: 'Benign prostatic hyperplasia', correct: true },
      { text: 'Prostate adenocarcinoma', correct: false },
      { text: 'Acute prostatitis', correct: false },
      { text: 'Neurogenic bladder', correct: false },
    ],
    explanation: 'A symmetrically enlarged, smooth prostate with LUTS in a 65-year-old is classic for BPH. PSA may be mildly elevated (4-10 ng/mL gray zone) in BPH. Prostate cancer often presents with a hard, nodular, asymmetric prostate. Prostatitis has fever and pain.',
  },

  // ── Cross-Cutting — Ethics & Preventive (2 questions) ──────────────────
  {
    id: 'dx_ethics_01',
    domain: 'CrossCutting',
    subtopic: 'Medical Ethics',
    question: 'A 17-year-old unmarried female presents to the clinic requesting an abortion at 8 weeks gestation. Under Saudi law, in which of the following scenarios is a therapeutic abortion legally permissible?',
    options: [
      { text: 'At the patient\'s request with parental consent', correct: false },
      { text: 'If continuing the pregnancy poses a risk to the mother\'s life and a medical committee approves', correct: true },
      { text: 'If the pregnancy resulted from rape with police report', correct: false },
      { text: 'If the fetus is diagnosed with Down syndrome', correct: false },
    ],
    explanation: 'Abortion in Saudi Arabia is generally prohibited but is permitted if a medical committee confirms that continuing the pregnancy poses a significant risk to the mother\'s life or health. Fetal anomalies incompatible with life may also be considered. Social or fetal non-lethal indications are not valid.',
  },
  {
    id: 'dx_ethics_02',
    domain: 'CrossCutting',
    subtopic: 'Preventive Medicine',
    question: 'A 50-year-old Saudi male presents for a preventive health visit. He has a BMI of 28, is a current smoker, and has a family history of colon cancer in his father at age 55. At what age should colorectal cancer screening begin for this patient?',
    options: [
      { text: 'Age 45', correct: true },
      { text: 'Age 40', correct: false },
      { text: 'Age 50', correct: false },
      { text: 'Already overdue — screen immediately', correct: false },
    ],
    explanation: 'The Saudi CRC screening guidelines recommend starting at age 45 for average-risk individuals. This patient\'s father had CRC at 55, but that does not meet criteria for high-risk (would need a first-degree relative diagnosed at <50 years). If it were age <50, screening would begin at 40.',
  },
];
